version: '3.8'

services:
  apache:
    image: httpd
    ports:
      - "8080:80"
    volumes:
      - /compose-projeto/site/:/usr/local/apache2/htdocs
    networks:
      - minha-rede

networks:
  minha-rede:
    driver: bridge
